build:
  environment:
    php:
      version: '7.1'
checks:
  php:
      psr2_switch_declaration: true
      psr2_class_declaration: true
      no_short_open_tag: true
      deprecated_code_usage: true
      code_rating: true
filter:
  excluded_paths:
    - bin/
    - tests/
tools:
  php_code_sniffer:
    config:
      standard: PSR2
