<?php
/**
 * @var \Bluz\Grid\Grid $grid
 * @var \Bluz\View\View $this
 */
?>
<script>
  // use data-spy="grid" for use AJAX for reload grid
  require(['bluz.grid']);
</script>

<div class="clearfix" data-spy="grid" data-grid="<?= $grid->getUid() ?>">
  <nav class="navbar navbar-light bg-light justify-content-between">
    <div>
      <a href="<?= $grid->filter('markRead', 'eq', '', true) ?>" class="btn <?= (
          $grid->getFilter('markRead', 'eq') === null && $grid->getFilter('markRead', 'ne') === null ? 'btn-info' : 'btn-secondary'
        ) ?>" data-ajax>all</a>
      <a href="<?= $grid->filter('markRead', 'ne', 1) ?>" class="btn <?= (
          $grid->getFilter('markRead', 'ne') ? 'btn-info' : 'btn-secondary'
        ) ?>" data-ajax>Unread</a>
      <a href="<?= $grid->filter('markRead', 'eq', 1) ?>" class="btn <?= (
          $grid->getFilter('markRead', 'eq') ? 'btn-info' : 'btn-secondary'
        ) ?>" data-ajax>Read</a>
    </div>
    <form action="<?= $this->url('contact-us', 'grid') ?>" class="form-inline filter-form" data-ajax>
      <div class="input-group">
          <?php echo
          $this->partial(
              'grid/filter-search.phtml',
              [
                  'grid' => $grid,
                  'filters' => [
                      'name' => __('Name'),
                      'email' => __('Email'),
                      'subject' => __('Subject'),
                      'message' => __('Message'),
                  ]
              ]
          )
          ?>
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="submit"><?= __("Search") ?></button>
        </span>
      </div>
    </form>
  </nav>
  <hr/>

  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table table-hover grid">
    <thead>
    <tr>
      <th><?= __('Id') ?></th>
      <th><a href="<?= $grid->order('name') ?: '#' ?>"><?= __('Name') ?></a></th>
      <th><a href="<?= $grid->order('email') ?: '#' ?>"><?= __('Email') ?></a></th>
      <th width="130px"><a href="<?= $grid->order('subject') ?: '#' ?>"><?= __('Subject') ?></a></th>
      <th><a href="<?= $grid->order('markRead') ?: '#' ?>"><?= __('Read') ?></a></th>
      <th><a href="<?= $grid->order('markAnswered') ?: '#' ?>"><?= __('Answered') ?></a></th>
      <th><a href="<?= $grid->order('created') ?>"><?= __('Created') ?></a></th>
      <th width="180px"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $row) : ?>
      <tr data-id="<?= $row['id'] ?>" class="<?= ($row['markRead'] === 0) ? 'bold' : '' ?>">
        <td><?= $row['id'] ?></td>
        <td><?= $row['userId']
                ? $this->ahref(esc($row['name']), ['users', 'profile', ['id' => $row['userId']]])
                : esc($row['name']) ?></td>
        <td><a href="mailto:<?= $row['email'] ?>"><?= $row['email'] ?></a></td>
        <td>
          <a id="subject" href="<?= $this->url('contact-us', 'read', ['id' => $row['id']]) ?>"
             data-ajax-dialog data-ajax-method="get" data-modal-style="width:700px;">
              <?= esc($row['subject']) ?>
          </a>
        </td>
        <td>
          <a id="read" href="<?= $this->url('contact-us', 'read', ['id' => $row['id']]) ?>" class="btn"
             data-ajax>
            <i class="fa <?= ($row['markRead']) ? 'fa-check-square-o' : 'fa-square-o' ?>"></i>
          </a>
        </td>
        <td>
          <a id="answer" href="<?= $this->url('contact-us', 'answer', ['id' => $row['id']]) ?>" class="btn"
             data-ajax>
            <i class="fa <?= ($row['markAnswered']) ? 'fa-check-square-o' : 'fa-square-o' ?>"></i>
          </a>
        </td>
        <td><?= $row['created'] ?></td>
        <td class="controls">
          <a href="<?= $this->url('contact-us', 'reply', ['id' => $row['id']]) ?>"
             class="btn btn-secondary btn-xs reply"
             data-ajax-dialog data-ajax-method="get" data-modal-style="width:700px;">
            <i class="fa fa-share"></i>
          </a>
          <a href="<?= $this->url('contact-us', 'crud', ['id' => $row['id']]) ?>" class="btn btn-primary"
             data-ajax-dialog data-ajax-method="get" data-modal-style="width:700px">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<?= $this->url('contact-us', 'crud', ['id' => $row['id']]) ?>" class="btn btn-danger"
             data-confirm data-ajax data-ajax-method="delete">
            <i class="fa fa-trash-o"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

    <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

  <script>
    require(['jquery'], function ($) {
      $(function () {
        $('#read, #answer').on('success.bluz.ajax', function () {
          let icon = $(this).find('i');
          (icon.hasClass('fa-square-o') && icon.removeClass()) ? icon.addClass('fa-check-square-o fa') : icon.addClass('fa-square-o fa')
        });
      })
    })
  </script


</div>
