<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_', false); ?>
<form id="<?= $uid ?>" class="form-horizontal" data-ajax method="post" action="<?= $this->url('contact-us', 'index') ?>"
      enctype="application/x-www-form-urlencoded">
  <div class="modal-header">
    <h3 class="modal-title"><?= __('Contact us') ?></h3>
  </div>
  <div class="modal-body">
    <?php if ($this->user()) : ?>
      <div class="form-group row">
        <label for="subject" class="col-form-label col-lg-2"><?= __('Subject') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="subject" name="subject" value="<?=esc($subject)?>" required/>
        </div>
      </div>
      <div class="form-group row">
        <label for="content" class="col-form-label col-lg-2"><?= __('Message') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
              <textarea rows="5" cols="10" id="content" class="form-control redactor" name="message"
                        required></textarea>
        </div>
      </div>
    <?php else : ?>
      <div class="form-group row">
        <label for="name" class="col-form-label col-lg-2"><?= __('Name') ?>:<sup class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="name" name="name" value="<?=esc($name)?>" required/>
        </div>
      </div>
      <div class="form-group row">
        <label for="email" class="col-form-label col-lg-2"><?= __('Email') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="email" class="form-control" id="email" name="email" value="<?=esc($email)?>" required/>
        </div>
      </div>
      <div class="form-group row">
        <label for="subject" class="col-form-label col-lg-2"><?= __('Subject') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="subject" name="subject" value="<?=esc($subject)?>" required/>
        </div>
      </div>
      <div class="form-group row">
        <label for="content" class="col-form-label col-lg-2"><?= __('Message') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
              <textarea rows="12" cols="26" id="content" class="form-control redactor" name="message"
                        required><?=esc($message)?></textarea>
        </div>
      </div>
      <?php $this->headScript('https://www.google.com/recaptcha/api.js'); ?>
      <div class="form-group row">
        <label class="col-lg-2"></label>
        <div class="col-lg-6">
          <div class="g-recaptcha" data-sitekey="<?= $siteKey ?>"></div>
        </div>
      </div>
    <?php endif; ?>
  </div>
  <div class="modal-footer">
    <div class="form-group">
      <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
    </div>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    echo $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>
