<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_', false); ?>
<h3><?= __('Contact us') ?></h3>
<form id="<?= $uid ?>" class="form-horizontal ajax" method="post" action="<?= $this->url('contact-us', 'index') ?>"
      enctype="application/x-www-form-urlencoded">
    <?php if ($this->user()) { ?>
      <div class="form-group">
        <label for="subject" class="control-label col-lg-2"><?= __('Subject') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="subject" name="subject" required/>
        </div>
      </div>
      <div class="form-group">
        <label for="content" class="control-label col-lg-2"><?= __('Message') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
              <textarea rows="5" cols="10" id="content" class="form-control redactor" name="message"
                        required></textarea>
        </div>
      </div>
    <?php } else { ?>
      <div class="form-group">
        <label for="name" class="control-label col-lg-2"><?= __('Name') ?>:<sup class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="name" name="name" required/>
        </div>
      </div>

      <div class="form-group">
        <label for="email" class="control-label col-lg-2"><?= __('Email') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="email" class="form-control" id="email" name="email" required/>
        </div>
      </div>

      <div class="form-group">
        <label for="subject" class="control-label col-lg-2"><?= __('Subject') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
          <input type="text" class="form-control" id="subject" name="subject" required/>
        </div>
      </div>

      <div class="form-group">
        <label for="content" class="control-label col-lg-2"><?= __('Message') ?>:<sup
              class="text-danger">*</sup></label>
        <div class="col-lg-6">
              <textarea rows="12" cols="26" id="content" class="form-control redactor" name="message"
                        required></textarea>
        </div>
      </div>

        <?php $this->headScript('https://www.google.com/recaptcha/api.js'); ?>
      <div class="form-group">
        <label class="col-lg-2"></label>
        <div class="col-lg-6">
          <div class="g-recaptcha" data-sitekey="<?= $siteKey ?>"></div>
        </div>
      </div>

    <?php } ?>
  <div class="form-group">
    <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    echo $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>
