<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<form class="form-horizontal" method="post" action="<?= $this->url('contact-us', 'reply') ?>" data-ajax
      enctype="application/x-www-form-urlencoded">
<div class="modal-header">
  <h4 class="modal-title"><?= __('Reply') ?></h4>
  <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
</div>
<div class="modal-body">
  <dl class="row">
    <dt class="col-lg-2"><?= __('Name') ?></dt>
    <dd class="col-lg-10">
      <?php if ($row['userId']): ?>
        <a href="<?=$this->url('users', 'profile', ['id' => $row['userId']])?>">
            <?= esc($row['name']) ?>
        </a>
      <?php else: ?>
        <?= esc($row['name']) ?>
      <?php endif; ?>
    </dd>
    <dt class="col-lg-2"><?= __('Email') ?></dt>
    <dd class="col-lg-10"><a href="mailto:<?= $row['email'] ?>"><?= $row['email'] ?></a></dd>
    <dt class="col-lg-2"><?= __('Posted') ?></dt>
    <dd class="col-lg-10"><?= $row['created'] ?></dd>
  </dl>
  <hr/>
  <h4><?= esc($row['subject']) ?></h4>
  <p><?= esc($row['message']) ?></p>
  <hr/>
  <h4><?= __('Answer') ?></h4>
  <input type="hidden" name="id" value="<?= $row['id'] ?>">
  <textarea rows="5" cols="6" id="content" class="form-control redactor" name="message" required></textarea>
</div>
<div class="modal-footer">
  <button type="submit" class="btn btn-primary"><?= __('Reply') ?></button>
  <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
</div>
</form>
