<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<form class="form-horizontal ajax" method="post" action="<?= $this->url('contact-us', 'reply') ?>"
      enctype="application/x-www-form-urlencoded">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title"><?= __('Reply') ?></h4>
</div>
<div class="modal-body">
  <dl class="dl-horizontal">
    <dt><?= __('Name') ?></dt>
    <dd>
      <?php if ($row['userId']): ?>
        <a href="<?=$this->url('users', 'profile', ['id' => $row['userId']])?>">
            <?= esc($row['name']) ?>
        </a>
      <?php else: ?>
        <?= esc($row['name']) ?>
      <?php endif; ?>
    </dd>
    <dt><?= __('Email') ?></dt>
    <dd><a href="mailto:<?= $row['email'] ?>"><?= $row['email'] ?></a></dd>
    <dt><?= __('Posted') ?></dt>
    <dd><?= $row['created'] ?></dd>
  </dl>
  <h4><?= esc($row['subject']) ?></h4>
  <p><?= esc($row['message']) ?></p>
  <h4><?= __('Reply') ?></h4>
    <input type="hidden" name="id" value="<?= $row['id'] ?>">
    <div class="form-group">
      <div class="col-lg-8">
        <textarea rows="5" cols="6" id="content" class="form-control redactor" name="message" required></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-6">
      </div>
    </div>
</div>
<div class="modal-footer">
  <button type="submit" class="btn btn-primary"><?= __('Reply') ?></button>
  <a href="#" class="btn btn-default" data-dismiss="modal"><?= __('Close') ?></a>
</div>
</form>
